sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nahid08/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nahid08/react-test npm test

after_success:
  - docker build -t nahid08/multi-client ./client
  - docker build -t nahid08/multi-nginx ./nginx
  - docker build -t nahid08/multi-server ./server
  - docker build -t nahid08/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nahid08/multi-client
  - docker push nahid08/multi-nginx
  - docker push nahid08/multi-server
  - docker push nahid08/multi-worker


deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-443118411418'
  bucket_path: 'docker-multi'
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY

